<?php

namespace App\DataFixtures;

use App\Entity\Rubriques;
use App\Entity\SousRubriques;
use App\Entity\Commandes;
use App\Entity\Compose;
use App\Entity\Contiens;
use App\Entity\Fournie;
use App\Entity\Fournisseurs;
use App\Entity\Livraison;
use App\Entity\Produits;
use App\Entity\Utilisateurs;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class AppFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        
        $rub1 = new Rubriques();
        $rub2 = new Rubriques();
        $rub3 = new Rubriques();
        $rub1->setnom("Instruments");
        $rub2->setnom("Materiel");
        $rub3->setnom("Partitions");
        $rub1->setphoto("Instruments.png");
        $rub2->setphoto("Materiel.png");
        $rub3->setphoto("Partitions.png");
        $manager->persist($rub1);
        $manager->persist($rub2);
        $manager->persist($rub3);

        $srub1 = new SousRubriques();
        $srub1->setnom("Cordes");
        $srub1->setphoto("Cordes.png");
        $srub1->setrubrique($rub1);
        $manager->persist($srub1);
        $srub2 = new SousRubriques();
        $srub2->setnom("Vents");
        $srub2->setphoto("Vents.png");
        $srub2->setrubrique($rub1);
        $manager->persist($srub2);
        $srub3 = new SousRubriques();
        $srub3->setnom("Claviers");
        $srub3->setphoto("Claviers.png");
        $srub3->setrubrique($rub1);
        $manager->persist($srub3);
        $srub4 = new SousRubriques();
        $srub4->setnom("Son");
        $srub4->setphoto("Son.png");
        $srub4->setrubrique($rub2);
        $manager->persist($srub4);
        $srub5 = new SousRubriques();
        $srub5->setnom("Accessoires");
        $srub5->setphoto("Accessoires.png");
        $srub5->setrubrique($rub2);
        $manager->persist($srub5);
        $srub6 = new SousRubriques();
        $srub6->setnom("Classique");
        $srub6->setphoto("Classique.png");
        $srub6->setrubrique($rub3);
        $manager->persist($srub6);
        $srub7 = new SousRubriques();
        $srub7->setnom("Rock");
        $srub7->setphoto("Rock.png");
        $srub7->setrubrique($rub3);
        $manager->persist($srub7);

        $pro1 = new Produits();
        $pro1->setnom("Violon");
        $pro1->setdescription("Instrument à cordes frottés ");
        $pro1->setPrixAchat(150.00);
        $pro1->setPrixVente(175.00);
        $pro1->setphoto("Violon.png");
        $pro1->setstock(17);
        $pro1->setSousRubrique($srub1);
        $manager->persist($pro1);
        $pro2 = new Produits();
        $pro2->setnom("Guitare");
        $pro2->setdescription("Instruent a corde lorem ipsum");
        $pro2->setPrixAchat(200.00);
        $pro2->setPrixVente(250.00);
        $pro2->setphoto("Guitare.png");
        $pro2->setstock(12);
        $pro2->setSousRubrique($srub1);
        $manager->persist($pro2);
        $pro3 = new Produits();
        $pro3->setnom("Flute");
        $pro3->setdescription("Flute a bec");
        $pro3->setPrixAchat(30.00);
        $pro3->setPrixVente(45.00);
        $pro3->setphoto("Flute.png");
        $pro3->setstock(103);
        $pro3->setSousRubrique($srub2);
        $manager->persist($pro3);
        $pro4 = new Produits();
        $pro4->setnom("Trompette");
        $pro4->setdescription("Trompette Trompette");
        $pro4->setPrixAchat(150.00);
        $pro4->setPrixVente(200.00);
        $pro4->setphoto("Trompette.png");
        $pro4->setstock(12);
        $pro4->setSousRubrique($srub2);
        $manager->persist($pro4);
        $pro5 = new Produits();
        $pro5->setnom("Harmonica");
        $pro5->setdescription("Parfait pour débutant");
        $pro5->setPrixAchat(50.00);
        $pro5->setPrixVente(60.00);
        $pro5->setphoto("Harmonica.png");
        $pro5->setstock(396);
        $pro5->setSousRubrique($srub2);
        $manager->persist($pro5);
        $pro6 = new Produits();
        $pro6->setnom("Piano droit");
        $pro6->setdescription("RushE point mp4");
        $pro6->setPrixAchat(2000.00);
        $pro6->setPrixVente(3500.00);
        $pro6->setphoto("PianoDroit.png");
        $pro6->setstock(4);
        $pro6->setSousRubrique($srub3);
        $manager->persist($pro6);
        $pro7 = new Produits();
        $pro7->setnom("Piano à queue");
        $pro7->setdescription("Très gros");
        $pro7->setPrixAchat(5000.00);
        $pro7->setPrixVente(7500.00);
        $pro7->setphoto("PianoAQueue.png");
        $pro7->setstock(2);
        $pro7->setSousRubrique($srub3);
        $manager->persist($pro7);
        $pro8 = new Produits();
        $pro8->setnom("Micro");
        $pro8->setdescription("Pour être mieux entendu");
        $pro8->setPrixAchat(50.00);
        $pro8->setPrixVente(75.00);
        $pro8->setphoto("Micro.png");
        $pro8->setstock(99);
        $pro8->setSousRubrique($srub4);
        $manager->persist($pro8);
        $pro9 = new Produits();
        $pro9->setnom("Casque");
        $pro9->setdescription("Pour mieux entendre");
        $pro9->setPrixAchat(30.00);
        $pro9->setPrixVente(50.00);
        $pro9->setphoto("Casque.png");
        $pro9->setstock(54);
        $pro9->setSousRubrique($srub4);
        $manager->persist($pro9);
        $pro10 = new Produits();
        $pro10->setnom("Cable Jack");
        $pro10->setdescription("Cable");
        $pro10->setPrixAchat(3.00);
        $pro10->setPrixVente(8.00);
        $pro10->setphoto("CableJack.png");
        $pro10->setstock(77);
        $pro10->setSousRubrique($srub5);
        $manager->persist($pro10);
        $pro11 = new Produits();
        $pro11->setnom("Mediator");
        $pro11->setdescription("Pour guitare");
        $pro11->setPrixAchat(0.50);
        $pro11->setPrixVente(1.00);
        $pro11->setphoto("Mediator.png");
        $pro11->setstock(1670);
        $pro11->setSousRubrique($srub5);
        $manager->persist($pro11);
        $pro12 = new Produits();
        $pro12->setnom("Colophane");
        $pro12->setdescription("Pour violon");
        $pro12->setPrixAchat(1.00);
        $pro12->setPrixVente(2.00);
        $pro12->setphoto("Colophane.png");
        $pro12->setstock(68);
        $pro12->setSousRubrique($srub5);
        $manager->persist($pro12);
        $pro13 = new Produits();
        $pro13->setnom("Les Noces de Figaro");
        $pro13->setdescription("Par Mozart");
        $pro13->setPrixAchat(25.00);
        $pro13->setPrixVente(30.00);
        $pro13->setphoto("Mozart.png");
        $pro13->setstock(12);
        $pro13->setSousRubrique($srub6);
        $manager->persist($pro13);
        $pro14 = new Produits();
        $pro14->setnom("Here Comes the Sun");
        $pro14->setdescription("Par Les beatles");
        $pro14->setPrixAchat(15.00);
        $pro14->setPrixVente(17.00);
        $pro14->setphoto("Beatles.png");
        $pro14->setstock(24);
        $pro14->setSousRubrique($srub7);
        $manager->persist($pro14);
        $pro15 = new Produits();
        $pro15->setnom("Something in the way");
        $pro15->setdescription("Par Nirvana");
        $pro15->setPrixAchat(5.00);
        $pro15->setPrixVente(7.00);
        $pro15->setphoto("Nirvana.png");
        $pro15->setstock(12);
        $pro15->setSousRubrique($srub7);
        $manager->persist($pro15);
        





        $uti1 = new Utilisateurs();
        $uti1->setnom("Dupont");
        $uti1->setprenom("Maurice");
        $uti1->setrole("Admin");
        $uti1->setreduction(100.00);
        $uti1->settelephon("0648722296");
        $uti1->setadresse("26 bis Avenue LeClerc");
        $uti1->setville("Paris");
        $uti1->setemail("mdupont@gmail.com");
        $manager->persist($uti1);
        $uti2 = new Utilisateurs();
        $uti2->setnom("Boucher");
        $uti2->setprenom("Marie");
        $uti2->setrole("Employé");
        $uti2->setreduction("50.00");
        $uti2->settelephon("0633487182");
        $uti2->setadresse("01 Rue des trois choux");
        $uti2->setville("Paris");
        $uti2->setemail("mboucher@gmail.com");
        $uti2->setreferent($uti1);
        $manager->persist($uti2);
        $uti3 = new Utilisateurs();
        $uti3->setnom("Lemoine");
        $uti3->setprenom("Frédérique");
        $uti3->setrole("Employé");
        $uti3->setreduction("50.00");
        $uti3->settelephon("0631876412");
        $uti3->setadresse("06 Rue du chat");
        $uti3->setville("Paris");
        $uti3->setemail("flemoine@gmail.com");
        $uti3->setreferent($uti1);
        $manager->persist($uti3);
        $uti4 = new Utilisateurs();
        $uti4->setnom("Chateau");
        $uti4->setprenom("Coralie");
        $uti4->setrole("Client");
        $uti4->setreduction("00.00");
        $uti4->settelephon("0613884011");
        $uti4->setadresse("37 Place du phare");
        $uti4->setville("Brest");
        $uti4->setemail("coracora@hotmail.fr");
        $uti4->setreferent($uti2);
        $manager->persist($uti4);
        $uti5 = new Utilisateurs();
        $uti5->setnom("Rabbit");
        $uti5->setprenom("Roger");
        $uti5->setrole("Client");
        $uti5->setreduction("00.00");
        $uti5->settelephon("0647512335");
        $uti5->setadresse("80 Rue DeVinci");
        $uti5->setville("Amiens");
        $uti5->setemail("quiveuxmapeau@gmail.com");
        $uti5->setreferent($uti3);
        $manager->persist($uti5);
        $uti6 = new Utilisateurs();
        $uti6->setnom("Bouvier");
        $uti6->setprenom("Camille");
        $uti6->setrole("Clientpro");
        $uti6->setreduction("10.00");
        $uti6->settelephon("0648777752");
        $uti6->setadresse("7 Rue du nuage");
        $uti6->setville("Flixecourt");
        $uti6->setemail("kmille@hotmail.fr");
        $uti6->setreferent($uti2);
        $manager->persist($uti6);

        $foureur1 = new Fournisseurs();
        $foureur1->setgerant($uti2);
        $foureur1->setnom("LucasLutier");
        $foureur1->settelephone("0679888531");
        $foureur1->setadresse("66 Rue du Violon");
        $foureur1->setville("Bordeaux");
        $manager->persist($foureur1);
        $foureur2 = new Fournisseurs();
        $foureur2->setgerant($uti2);
        $foureur2->setnom("PartitionsCo");
        $foureur2->settelephone("0694030250");
        $foureur2->setadresse("7 Avenue Rouge");
        $foureur2->setville("Amiens");
        $manager->persist($foureur2);
        $foureur3 = new Fournisseurs();
        $foureur3->setgerant($uti3);
        $foureur3->setnom("Pianpian");
        $foureur3->settelephone("0645555578");
        $foureur3->setadresse("1 bis Rue Jean-Claude");
        $foureur3->setville("Flixecourt");
        $manager->persist($foureur3);
        $foureur4 = new Fournisseurs();
        $foureur4->setgerant($uti2);
        $foureur4->setnom("Axe&Soir");
        $foureur4->settelephone("0606477415");
        $foureur4->setadresse("55 Boulevard des Champignons");
        $foureur4->setville("Paris");
        $manager->persist($foureur4);
        $foureur5 = new Fournisseurs();
        $foureur5->setgerant($uti2);
        $foureur5->setnom("Vent et cuivre");
        $foureur5->settelephone("0719856544");
        $foureur5->setadresse("9 Rue du Petit Nuage");
        $foureur5->setville("Paris");
        $manager->persist($foureur5);

        $livr1 = new Livraison();
        $livr1->setutilisateur($uti4);
        $livr1->setdate(new \DateTime('now'));
        $manager->persist($livr1);
        $livr2 = new Livraison();
        $livr2->setutilisateur($uti4);
        $livr2->setdate(new \DateTime('now'));
        $manager->persist($livr2);
        $livr3 = new Livraison();
        $livr3->setutilisateur($uti5);
        $livr3->setdate(new \DateTime('now'));
        $manager->persist($livr3);


        $cont1 = new Contiens();
        $cont1->setproduit($pro5);
        $cont1->setlivraison($livr1);
        $cont1->setquantite(2);
        $manager->persist($cont1);
        $cont2 = new Contiens();
        $cont2->setproduit($pro11);
        $cont2->setlivraison($livr1);
        $cont2->setquantite(7);
        $manager->persist($cont2);
        $cont3 = new Contiens();
        $cont3->setproduit($pro2);
        $cont3->setlivraison($livr2);
        $cont3->setquantite(1);
        $manager->persist($cont3);

        $com1 = new Commandes();
        $com1->setutilisateur($uti4);
        $com1->setdate(new \DateTime('now'));
        $com1->setreglement("carte");
        $com1->setAdresseLivraison("37 Place du phare");
        $com1->setAdresseFacturation("37 Place du phare");
        $manager->persist($com1);
        $com2 = new Commandes();
        $com2->setutilisateur($uti5);
        $com2->setdate(new \DateTime('now'));
        $com2->setreglement("carte");
        $com2->setAdresseLivraison("80 Rue DeVinci");
        $com2->setAdresseFacturation("80 Rue DeVinci");
        $manager->persist($com2);
        $com3 = new Commandes();
        $com3->setutilisateur($uti6);
        $com3->setdate(new \DateTime('now'));
        $com3->setreglement("virement");
        $com3->setAdresseLivraison("7 Rue du nuage");
        $com3->setAdresseFacturation("3 Rue du nuage");
        $manager->persist($com3);

        $comp1 = new Compose();
        $comp1->setproduit($pro3);
        $comp1->setcommande($com1);
        $comp1->setquantite(1);
        $comp1->setreduction(0.00);
        $manager->persist($comp1);
        $comp2 = new Compose();
        $comp2->setproduit($pro4);
        $comp2->setcommande($com1);
        $comp2->setquantite(1);
        $comp2->setreduction(0.00);
        $manager->persist($comp2);
        $comp3 = new Compose();
        $comp3->setproduit($pro11);
        $comp3->setcommande($com2);
        $comp3->setquantite(12);
        $comp3->setreduction(0.00);
        $manager->persist($comp3);
        $comp4 = new Compose();
        $comp4->setproduit($pro7);
        $comp4->setcommande($com3);
        $comp4->setquantite(1);
        $comp4->setreduction(0.00);
        $manager->persist($comp4);

        $fou1 = new Fournie();
        $fou1->setproduit($pro4);
        $fou1->setfournisseur($foureur5);
        $fou1->setquantite(2);
        $fou1->setdate(new \DateTime('now'));
        $manager->persist($fou1);
        $fou2 = new Fournie();
        $fou2->setproduit($pro3);
        $fou2->setfournisseur($foureur5);
        $fou2->setquantite(35);
        $fou2->setdate(new \DateTime('now'));
        $manager->persist($fou2);
        $fou3 = new Fournie();
        $fou3->setproduit($pro14);
        $fou3->setfournisseur($foureur2);
        $fou3->setquantite(7);
        $fou3->setdate(new \DateTime('now'));
        $manager->persist($fou3);
        $fou4 = new Fournie();
        $fou4->setproduit($pro1);
        $fou4->setfournisseur($foureur1);
        $fou4->setquantite(1);
        $fou4->setdate(new \DateTime('now'));
        $manager->persist($fou4);




        $manager->flush();
    }
}
