index:
  path: /
  controller: App\Controller\IndexController::index

souscategories:
  path: /souscategories
  controller: App\Controller\SouscategoriesController::index0

app_souscategories2:
  path: /souscategories/{rubrique_id}
  controller: App\Controller\SouscategoriesController::index


produits:
  path: /produits
  controller: App\Controller\ProduitsController::index

app_produits2:
  path: /produits/{sous_rubrique_id}
  controller: App\Controller\ProduitsController::index2


register:
  path: /register
  controller: App\Controller\RegisterController::register


login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout
  controller: App\Controller\SecurityController::logout


panier:
  path: /panier
  controller: App\Controller\PanierController::index


panier_add:
  path: /panier/add/{produits_id}
  controller: App\Controller\PanierController::addToRoute


panier_removeall:
  path: /panier/removeAll
  controller: App\Controller\PanierController::removeAll


panier_remove:
  path: /panier/remove/{produits_id}
  controller: App\Controller\PanierController::removeToPanier


panier_decrease:
  path: /panier/decrease/{produits_id}
  controller: App\Controller\PanierController::decreaseToRoute





dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index


#controllers:
#  resource:
 #   path: ../src/Controller/
  #  namespace: App\Controller
 # type: attribute

