index:
  path: /
  controller: App\Controller\IndexController::index

souscategories:
  path: /souscategories
  controller: App\Controller\SouscategoriesController::index0

app_souscategories2:
  path: /souscategories/{rubrique_id}
  controller: App\Controller\SouscategoriesController::index


produits:
  path: /produits
  controller: App\Controller\ProduitsController::index

app_produits2:
  path: /produits/{sous_rubrique_id}
  controller: App\Controller\ProduitsController::index2


register:
  path: /register
  controller: App\Controller\RegisterController::register


dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index


#controllers:
#  resource:
 #   path: ../src/Controller/
  #  namespace: App\Controller
 # type: attribute

