index:
  path: /
  controller: App\Controller\IndexController::index

souscategories:
  path: /souscategories
  controller: App\Controller\SouscategoriesController::index

produits:
  path: /produits
  controller: App\Controller\ProduitsController::index